### ISSUE TITLE
nps内网穿透问题

### ISSUE THREAD

**Issue by waphbs** [Ameykyl/openwrt18.06#15]
内网穿透客户端的服务器只能填ip地址,不能用域名,我的服务端是动态ip,求解决

还有一个nps不能断线重连,必须手动关闭在打开一次才能正常链接,或是重启路由器才能解决问题

感谢大佬的固件

**Comment by waphbs** [comment]
能否在op上加上nps的服务端,或是有安装ipk么,感谢

**Comment by Ameykyl** [comment]
自定义插件可以加入任何源码编译

**Comment by waphbs** [comment]
刚刚又测试了一波,重启路由器后nps客户端也是无法链接，必须手动关闭在打开一次才能正常链接

**Comment by waphbs** [comment]
自定义插件可以加入任何源码编译


小白一个,不会整大咖,您费费心解决下吧,感谢
